POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "51d538b8-df6a-40e3-aad6-523b5751bc4c"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a1",
    "account_id_to": "a2",
    "amount": 100
}

### 

GET http://localhost:3003/balances/a1 HTTP/1.1

###

GET http://localhost:3003/balances/a2 HTTP/1.1