
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe 1",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "51d538b8-df6a-40e3-aad6-523b5751bc4c"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "6da6b44d-9127-4b6c-9a99-bf68e3336d50",
    "account_id_to": "d59520c2-9077-477f-a65a-ea0b2feda2da",
    "amount": 1
}

### 

GET http://localhost:3003/balances/6da6b44d-9127-4b6c-9a99-bf68asd6d50 HTTP/1.1
